security:
  oauth2:
    client:
      clientId: 9782d347188b3f64970144a214caedea8d543d92fa01eeedd77fcb1477c05cd8
      clientSecret: e650873f8b6bc1b8eebdc67e81274f345ddd15e31bc21d12ae07cbdd7774ac13
      accessTokenUri: https://gitlab.com/oauth/token
      userAuthorizationUri: https://gitlab.com/oauth/authorize
    resource:
      userInfoUri: https://gitlab.com/api/v4/user
    sso:
      # 这句是默认的 不过还是加上吧. 在gitlab Callback URL里面填写 http://127.0.0.1:8080
      login-path: /login

logging:
  level:
    org.springframework.security: DEBUG